apiVersion: apps/v1
kind: Deployment
metadata:
  name: Jithubank
  labels:
    app: Jithubank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Jithubank
  template:
    metadata:
      labels:
        app: Jithubank
    spec:
      containers:
      - name: Jithubank
        image: jithendragurram/Jithubank:latest
        ports:
        - containerPort: 3000
